// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoFinal_AP1_AdonisMercado.DAL;

#nullable disable

namespace ProyectoFinal_AP1_AdonisMercado.Migrations.ContextoMigrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20251127152616_AddingVehicles")]
    partial class AddingVehicles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoFinal_AP1_AdonisMercado.Models.Distribuidor", b =>
                {
                    b.Property<int>("DistribuidorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistribuidorId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fax")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DistribuidorId");

                    b.ToTable("Distribuidores");
                });

            modelBuilder.Entity("ProyectoFinal_AP1_AdonisMercado.Models.Documento", b =>
                {
                    b.Property<int>("DocumentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentoId"));

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocumentoId");

                    b.HasIndex("PedidoId");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("ProyectoFinal_AP1_AdonisMercado.Models.Pedido", b =>
                {
                    b.Property<int>("PedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PedidoId"));

                    b.Property<int>("DistribuidorId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombrePedido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PedidoId");

                    b.HasIndex("DistribuidorId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("ProyectoFinal_AP1_AdonisMercado.Models.PedidoDetalle", b =>
                {
                    b.Property<int>("PedidoDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PedidoDetalleId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("PedidoDetalleId");

                    b.HasIndex("PedidoId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("PedidoDetalles");
                });

            modelBuilder.Entity("ProyectoFinal_AP1_AdonisMercado.Models.Vehiculo", b =>
                {
                    b.Property<int>("VehiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehiculoId"));

                    b.Property<int>("AnioFabricacion")
                        .HasColumnType("int");

                    b.Property<string>("ColorVehiculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoVehiculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarcaVehiculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModeloVehiculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroChasis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoCombustible")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VehiculoId");

                    b.ToTable("Vehiculos");

                    b.HasData(
                        new
                        {
                            VehiculoId = 1,
                            AnioFabricacion = 2020,
                            ColorVehiculo = "Blanco",
                            EstadoVehiculo = "Nuevo",
                            MarcaVehiculo = "Toyota",
                            ModeloVehiculo = "Corolla",
                            NumeroChasis = "JTDBR32E720045671",
                            Precio = 20000.00m,
                            TipoCombustible = "Gasolina"
                        },
                        new
                        {
                            VehiculoId = 2,
                            AnioFabricacion = 2019,
                            ColorVehiculo = "Negro",
                            EstadoVehiculo = "Usado",
                            MarcaVehiculo = "Honda",
                            ModeloVehiculo = "Civic",
                            NumeroChasis = "2HGFA16598H345612",
                            Precio = 18000.00m,
                            TipoCombustible = "Gasolina"
                        },
                        new
                        {
                            VehiculoId = 3,
                            AnioFabricacion = 2018,
                            ColorVehiculo = "Azul",
                            EstadoVehiculo = "Usado",
                            MarcaVehiculo = "Ford",
                            ModeloVehiculo = "Focus",
                            NumeroChasis = "1FAHP3F26CL123589",
                            Precio = 15000.00m,
                            TipoCombustible = "Diésel"
                        },
                        new
                        {
                            VehiculoId = 4,
                            AnioFabricacion = 2025,
                            ColorVehiculo = "Rojo",
                            EstadoVehiculo = "Nuevo",
                            MarcaVehiculo = "Chevrolet",
                            ModeloVehiculo = "Tahoe",
                            NumeroChasis = "1GNSKCKC4FR367812",
                            Precio = 115000.00m,
                            TipoCombustible = "Gasolina"
                        },
                        new
                        {
                            VehiculoId = 5,
                            AnioFabricacion = 2024,
                            ColorVehiculo = "Gris",
                            EstadoVehiculo = "Nuevo",
                            MarcaVehiculo = "Toyota",
                            ModeloVehiculo = "Hilux",
                            NumeroChasis = "MR0HA3CD205123678",
                            Precio = 52000.00m,
                            TipoCombustible = "Diesel"
                        },
                        new
                        {
                            VehiculoId = 6,
                            AnioFabricacion = 2023,
                            ColorVehiculo = "Blanco",
                            EstadoVehiculo = "Nuevo",
                            MarcaVehiculo = "Nissan",
                            ModeloVehiculo = "Sentra",
                            NumeroChasis = "3N1AB8CV4PY245781",
                            Precio = 22000.00m,
                            TipoCombustible = "Gasolina"
                        },
                        new
                        {
                            VehiculoId = 7,
                            AnioFabricacion = 2025,
                            ColorVehiculo = "Azul",
                            EstadoVehiculo = "Nuevo",
                            MarcaVehiculo = "Honda",
                            ModeloVehiculo = "CR-V",
                            NumeroChasis = "5J6RM4H77GL046821",
                            Precio = 55000.00m,
                            TipoCombustible = "Gasolina"
                        },
                        new
                        {
                            VehiculoId = 8,
                            AnioFabricacion = 2024,
                            ColorVehiculo = "Rojo",
                            EstadoVehiculo = "Nuevo",
                            MarcaVehiculo = "Mazda",
                            ModeloVehiculo = "CX-5",
                            NumeroChasis = "JM3KFBDM4M0557812",
                            Precio = 48000.00m,
                            TipoCombustible = "Gasolina"
                        },
                        new
                        {
                            VehiculoId = 9,
                            AnioFabricacion = 2023,
                            ColorVehiculo = "Blanco",
                            EstadoVehiculo = "Usado",
                            MarcaVehiculo = "Toyota",
                            ModeloVehiculo = "RAV4 Hybrid",
                            NumeroChasis = "JTMGB3FV2MD062345",
                            Precio = 35000.00m,
                            TipoCombustible = "Gasolina"
                        },
                        new
                        {
                            VehiculoId = 10,
                            AnioFabricacion = 2022,
                            ColorVehiculo = "Negro",
                            EstadoVehiculo = "Usado",
                            MarcaVehiculo = "Chevrolet",
                            ModeloVehiculo = "Silverado",
                            NumeroChasis = "1GCUYDED2MZ234567",
                            Precio = 60000.00m,
                            TipoCombustible = "Diesel"
                        },
                        new
                        {
                            VehiculoId = 11,
                            AnioFabricacion = 2026,
                            ColorVehiculo = "Gris",
                            EstadoVehiculo = "Nuevo",
                            MarcaVehiculo = "Toyota",
                            ModeloVehiculo = "RAV4",
                            NumeroChasis = "2T3J1RFV7RW345612",
                            Precio = 80000m,
                            TipoCombustible = "Gasolina"
                        },
                        new
                        {
                            VehiculoId = 12,
                            AnioFabricacion = 2026,
                            ColorVehiculo = "Gris",
                            EstadoVehiculo = "Nuevo",
                            MarcaVehiculo = "Kia",
                            ModeloVehiculo = "K5",
                            NumeroChasis = "5XXG64J20MG152487",
                            Precio = 59000m,
                            TipoCombustible = "Gasolina"
                        },
                        new
                        {
                            VehiculoId = 13,
                            AnioFabricacion = 2024,
                            ColorVehiculo = "Sky Blue",
                            EstadoVehiculo = "Usado",
                            MarcaVehiculo = "Honda",
                            ModeloVehiculo = "Pilot",
                            NumeroChasis = "5FNYF6H56LB123789",
                            Precio = 6000m,
                            TipoCombustible = "Gasolina"
                        },
                        new
                        {
                            VehiculoId = 14,
                            AnioFabricacion = 2026,
                            ColorVehiculo = "Rojo",
                            EstadoVehiculo = "Nuevo",
                            MarcaVehiculo = "Toyota",
                            ModeloVehiculo = "Tacoma TRD Pro",
                            NumeroChasis = "3TMCZ5AN8PM234981",
                            Precio = 120000m,
                            TipoCombustible = "Gasolina"
                        },
                        new
                        {
                            VehiculoId = 15,
                            AnioFabricacion = 2026,
                            ColorVehiculo = "Storm Cloud",
                            EstadoVehiculo = "Nuevo",
                            MarcaVehiculo = "Toyota",
                            ModeloVehiculo = "Highlander",
                            NumeroChasis = "5TDKDRBH4PS145678",
                            Precio = 110000m,
                            TipoCombustible = "Gasolina"
                        },
                        new
                        {
                            VehiculoId = 16,
                            AnioFabricacion = 2025,
                            ColorVehiculo = "Blanco",
                            EstadoVehiculo = "Usado",
                            MarcaVehiculo = "JETOUR",
                            ModeloVehiculo = "Dashing",
                            NumeroChasis = "L6T743DF5RA012345",
                            Precio = 38000m,
                            TipoCombustible = "Gasolina"
                        },
                        new
                        {
                            VehiculoId = 17,
                            AnioFabricacion = 2025,
                            ColorVehiculo = "Blanco",
                            EstadoVehiculo = "Nuevo",
                            MarcaVehiculo = "Hyundai",
                            ModeloVehiculo = "Sonata",
                            NumeroChasis = "5NPEJ4J27MH045612",
                            Precio = 40000m,
                            TipoCombustible = "Gasolina"
                        },
                        new
                        {
                            VehiculoId = 18,
                            AnioFabricacion = 2026,
                            ColorVehiculo = "Blanco",
                            EstadoVehiculo = "Nuevo",
                            MarcaVehiculo = "Kia",
                            ModeloVehiculo = "Sonet",
                            NumeroChasis = "MZK123F47RN654321",
                            Precio = 35000m,
                            TipoCombustible = "Gasolina"
                        },
                        new
                        {
                            VehiculoId = 19,
                            AnioFabricacion = 2025,
                            ColorVehiculo = "Blanco",
                            EstadoVehiculo = "Nuevo",
                            MarcaVehiculo = "Mercedes-Benz",
                            ModeloVehiculo = "GLE 63 S Coupe",
                            NumeroChasis = "4JGED7FB7MA123456",
                            Precio = 165000.00m,
                            TipoCombustible = "Gasolina"
                        },
                        new
                        {
                            VehiculoId = 20,
                            AnioFabricacion = 2025,
                            ColorVehiculo = "Gris",
                            EstadoVehiculo = "Nuevo",
                            MarcaVehiculo = "Nissan",
                            ModeloVehiculo = "Frontier Pro-4X",
                            NumeroChasis = "1N6ED1EK9RN345678",
                            Precio = 55000m,
                            TipoCombustible = "Diesel"
                        },
                        new
                        {
                            VehiculoId = 21,
                            AnioFabricacion = 2025,
                            ColorVehiculo = "Blanco",
                            EstadoVehiculo = "Usado",
                            MarcaVehiculo = "Toyota",
                            ModeloVehiculo = "Land Cruiser Prado Premium",
                            NumeroChasis = "JTEBR3FJ3RK128945",
                            Precio = 90000m,
                            TipoCombustible = "Gasolina"
                        });
                });

            modelBuilder.Entity("ProyectoFinal_AP1_AdonisMercado.Models.Documento", b =>
                {
                    b.HasOne("ProyectoFinal_AP1_AdonisMercado.Models.Pedido", "Pedido")
                        .WithMany("Documentos")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("ProyectoFinal_AP1_AdonisMercado.Models.Pedido", b =>
                {
                    b.HasOne("ProyectoFinal_AP1_AdonisMercado.Models.Distribuidor", "Distribuidor")
                        .WithMany("Pedidos")
                        .HasForeignKey("DistribuidorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Distribuidor");
                });

            modelBuilder.Entity("ProyectoFinal_AP1_AdonisMercado.Models.PedidoDetalle", b =>
                {
                    b.HasOne("ProyectoFinal_AP1_AdonisMercado.Models.Pedido", "Pedido")
                        .WithMany("PedidoDetalles")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoFinal_AP1_AdonisMercado.Models.Vehiculo", "Vehiculo")
                        .WithMany("PedidoDetalles")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("ProyectoFinal_AP1_AdonisMercado.Models.Distribuidor", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("ProyectoFinal_AP1_AdonisMercado.Models.Pedido", b =>
                {
                    b.Navigation("Documentos");

                    b.Navigation("PedidoDetalles");
                });

            modelBuilder.Entity("ProyectoFinal_AP1_AdonisMercado.Models.Vehiculo", b =>
                {
                    b.Navigation("PedidoDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
